#!/usr/bin/env bash
set -ex

cat > ../reverse-proxy/data/generated.service.home-automation.yml <<-EOF
http:
  routers:
    home-assistant:
      service: home-assistant
      rule: Host(\`home.$HOMELAB_BASE_DOMAIN\`)
      middlewares:
        - auth@file
      entrypoints:
        - web
        - websecure

  services:
    home-assistant:
      loadbalancer:
        servers:
          - url: http://$HOMELAB_HOST_LOCAL_IP:8123
EOF

docker-compose rm -f
