version: '2'

services:
  soulseek:
    image: slskd/slskd
    networks:
      - default
      - reverse-proxy
    user: ${HOMELAB_USER_ID}:${HOMELAB_GROUP_ID}
    env_file: env
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_DOWNLOADS_DIR=/storage/downloads
      - SLSKD_INCOMPLETE_DIR=/storage/downloads
      - SLSKD_SHARED_DIR=/storage/downloads
      - SLSKD_SHARE_CACHE_STORAGE_MODE=disk
      - SLSKD_NO_HTTPS=true
      - SLSKD_NO_VERSION_CHECK=true
      - SLSKD_NO_AUTH=true
      - SLSKD_UPLOAD_SPEED_LIMIT=100
      - SLSKD_DOWNLOAD_SPEED_LIMIT=2147483647
    ports:
      - 50300:50300
    volumes:
      - ./persistent/slskd:/app
      - ${HOMELAB_STORAGE_PATH}:/storage
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-soulseek.rule=Host(`soulseek.${HOMELAB_BASE_DOMAIN}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-soulseek.entrypoints=web,websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-soulseek.middlewares=auth@file
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-soulseek.loadbalancer.server.port=5030

      - dashboard.group=Downloads
      - dashboard.name=Music
      - dashboard.subtitle=Soulseek
      - dashboard.url=https://soulseek.${HOMELAB_BASE_DOMAIN}
      - dashboard.icon=fa fa-music

networks:
  reverse-proxy:
    external: true
