#!/usr/bin/env bash
set -ex

cat <<-EOF | docker run --rm -i --volume "$PWD:/data" alpine sh
mkdir -p /data/persistent/nextcloud
chown 33:0 /data/persistent/nextcloud

mkdir -p /data/persistent/db
chown 999:999 /data/persistent/db

mkdir -p /data/persistent/db-dump
chown 999:999 /data/persistent/db-dump

mkdir -p /data/persistent/elasticsearch
chown 1000 /data/persistent/elasticsearch

mkdir -p /data/persistent/redis
chown 999:1000 /data/persistent/redis
EOF
