version: "2.0"

services:
  main:
    image: traefik
    networks:
      - reverse-proxy
    command:
      - --api.insecure=true
      - --api.dashboard=true

      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=reverse-proxy

      # HTTP
      - --entrypoints.web.address=:80

      # HTTPS
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https

      # Wildcard Cert
      # - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=route53
      - --certificatesresolvers.letsencrypt.acme.email=wyatt.mike@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/output/acme.json
      - --entrypoints.websecure.http.tls.certresolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=${HOMELAB_BASE_DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${HOMELAB_BASE_DOMAIN}

      # Default middlewares, only applied to websecure because that's what
      # everything redirects to
      - --entrypoints.websecure.http.middlewares=standard@file

      # TODO Only for testing, should be permanent.
      - --entrypoints.web.http.redirections.entryPoint.permanent=false

      - --log.filePath=/output/log/traefik.log
      - --log.level=INFO
      - --accesslog=true
      - --accesslog.filepath=/output/log/access.log

      - --providers.file.directory=/config
      - --providers.file.watch=true
    env_file: env
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./persistent/traefik:/output
      - ./data:/config
    # labels:
    #   # Dashboard access
    #   - traefik.enable=true
    #   - traefik.http.routers.api.rule=Host(`traefik.${HOMELAB_BASE_DOMAIN}`)
    #   - traefik.http.routers.api.entrypoints=web,websecure
    #   - traefik.http.routers.api.service=api@internal
    #   - traefik.http.routers.api.middlewares=auth@file

networks:
  reverse-proxy:
    name: reverse-proxy
