#!/usr/bin/env bash
set -e

client_id=$(./script/generate-random --charset rfc3986 --length 32 | awk '{ print $3 }')
client_secret=$(./script/generate-random --charset rfc3986 --length 64 | awk '{ print $3 }')
client_secret_hash=$(./script/generate-hash-password "$client_secret" | awk '{ print $2 }')

echo "Client ID: ${client_id}"
echo "Client Secret: ${client_secret}"
echo "Client Secret Hash: ${client_secret_hash}"
echo "Client Secret Hash (Escaped for env files): ${client_secret_hash//\$/\$\$}"
