#!/usr/bin/env bash

mkdir -p persistent/authelia/

cat > ../reverse-proxy/data/generated.middleware.auth.yml <<-EOF
http:
  middlewares:
    auth:
      forwardAuth:
        # Using the internal container + port
        address: http://authelia:9091/api/authz/forward-auth
        trustForwardHeader: true
        authResponseHeaders:
          - Authorization
          - Proxy-Authorization
          - Remote-User
          - Remote-Groups
          - Remote-Email
          - Remote-Name

    auth-basic:
      forwardAuth:
        address: http://authelia:9091/api/verify?auth=basic
        trustForwardHeader: true
        authResponseHeaders:
          - Authorization
          - Proxy-Authorization
          - Remote-User
          - Remote-Groups
          - Remote-Email
          - Remote-Name
EOF
