version: "2"

services:
  server:
    image: gitea/gitea
    networks:
      - default
      - reverse-proxy
    environment:
      - USER_UID=${HOMELAB_USER_ID}
      - USER_GID=${HOMELAB_GROUP_ID}

      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea

      - GITEA__server__DOMAIN=git.${HOMELAB_BASE_DOMAIN}
      - GITEA__server__ROOT_URL=https://git.${HOMELAB_BASE_DOMAIN}
      - GITEA__server__SSH_DOMAIN=git.${HOMELAB_BASE_DOMAIN}
      # Because we're already using an HTTPS reverse proxy.
      - GITEA__server__PROTOCOL=http

      # OpenID
      - GITEA__openid__ENABLE_OPENID_SIGNIN=true
      - GITEA__openid__ENABLE_OPENID_SIGNUP=true
      - GITEA__openid__WHITELISTED_URIS=auth.${HOMELAB_BASE_DOMAIN}

      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__ALLOW_ONLY_INTERNAL_REGISTRATION=false
      - GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION=true
      - GITEA__service__SHOW_REGISTRATION_BUTTON=false

      - GITEA__oauth2_client__REGISTER_EMAIL_CONFIRM=false
      - GITEA__oauth2_client__ENABLE_AUTO_REGISTRATION=true
      - GITEA__oauth2_client__ACCOUNT_LINKING=login
      - GITEA__oauth2_client__USERNAME=preferred_username
      - GITEA__oauth2_client__OPENID_CONNECT_SCOPES=profile email groups

      - GITEA__APP_NAME=git.${HOMELAB_BASE_DOMAIN}
      - GITEA__service__REQUIRE_SIGNIN_VIEW=true

      # Indexing
      - GITEA__indexer__ISSUE_INDEXER_TYPE=bleve

      - GITEA__indexer__REPO_INDEXER_ENABLED=true
      - GITEA__indexer__REPO_INDEXER_TYPE=bleve
      - GITEA__indexer__REPO_INDEXER_REPO_TYPES=sources,forks,mirrors,templates

      # redis
      - GITEA__cache__ENABLED=true
      - GITEA__cache__ADAPTER=redis
      - GITEA__cache__HOST=redis://redis:6379/0
      - GITEA__session__PROVIDER=redis
      - GITEA__session__PROVIDER_CONFIG=redis://redis:6379/0
      - GITEA__queue__TYPE=redis
      - GITEA__queue__CONN_STR=redis://redis:6379/0

      # Actions
      - GITEA__actions__ENABLED=true

    volumes:
      - ./persistent/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-server.rule=Host(`git.${HOMELAB_BASE_DOMAIN}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-server.entrypoints=web,websecure
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-server.loadbalancer.server.port=3000

      - dashboard.group=Source Code
      - dashboard.name=Source Code
      - dashboard.subtitle=Gitea. Tap Sign in with Authelia.
      - dashboard.url=https://git.${HOMELAB_BASE_DOMAIN}
      - dashboard.icon=fa fa-code

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ./persistent/gitea-postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine

networks:
  reverse-proxy:
    external: true
