#!/usr/bin/env bash
set -e

TITLE="Homelab User Guide"

BIN_PATH="$(dirname "$(realpath "$0")")/../../../bin"
source "${BIN_PATH}/homelab-shell-env"

# Generate a docker env file that has all the homelab vars.
env | sort | grep ^HOMELAB > homelab-env

echo > combined_user_guide.md

find ../ -maxdepth 2 -name USER_GUIDE.md | sort | while read -r file; do
  cat "$file" >> combined_user_guide.md
  echo >> combined_user_guide.md
  echo >> combined_user_guide.md
done

# Replace env vars.
docker run --rm \
  --volume "$PWD:/app" \
  --env-file homelab-env \
  --env "HOMELAB_USER_GUIDES=$(cat combined_user_guide.md)" \
  --user "$HOMELAB_USER_ID:$HOMELAB_GROUP_ID" \
  node:lts-alpine \
  node /app/data/replaceEnvVars.js /app/README.md \
  > replaced.md

mkdir -p persistent/

# Turn the markdown into HTML.
docker run --rm \
  --volume "$PWD":/app \
  --user "$HOMELAB_USER_ID:$HOMELAB_GROUP_ID" \
  pandoc/core \
  /app/replaced.md \
  --from markdown+autolink_bare_uris \
  --to html5 \
  --include-in-header /app/gh-pandoc.css \
  --toc \
  --metadata "title=$TITLE" \
  --standalone \
  > "persistent/index.html"

# Cleanup and move files
cat <<-EOF | docker run --rm -i --volume "$PWD/../..:/data" --env HOMELAB_USER_ID --env HOMELAB_GROUP_ID alpine sh
rm /data/services/documentation/homelab-env
rm /data/services/documentation/combined_user_guide.md
mv /data/services/documentation/replaced.md "/data/ui/$TITLE.md"
cp /data/services/documentation/persistent/index.html "/data/ui/$TITLE.html"

chown \$HOMELAB_USER_ID:\$HOMELAB_GROUP_ID "/data/ui/$TITLE.md"
chown \$HOMELAB_USER_ID:\$HOMELAB_GROUP_ID "/data/ui/$TITLE.html"
EOF
