version: "2"

services:
  guacd:
    image: guacamole/guacd:1.5.4
    volumes:
      - ./persistent/data:/data

  guacamole:
    image: guacamole/guacamole:1.5.4
    networks:
      - default
      - reverse-proxy
    volumes:
      # I've heard Apache was bad at managing software, but oh my.
      # The backing functionality for getting groups from OpenID was added in
      # 2020: https://github.com/apache/guacamole-client/pull/564
      # ... and released in 2021 (1.3.0)
      # The PR adding support for `OPENID_SCOPE` was added in 2023:
      # https://github.com/apache/guacamole-client/commit/c9a7c7bae4a8e517b62c783dfccba11f8ca7c43e
      # ... but for some reason is slated for 1.6.0
      # It's a change to what environment variables are accepted in docker,
      # there's no good reason to hold this back other than bad management.
      - ./start.sh:/opt/guacamole/bin/start.sh
    env_file: env
    environment:
      - GUACD_HOSTNAME=${COMPOSE_PROJECT_NAME}-guacd-1
      - POSTGRESQL_HOSTNAME=${COMPOSE_PROJECT_NAME}-postgres-1
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres

      - OPENID_AUTHORIZATION_ENDPOINT=https://auth.${HOMELAB_BASE_DOMAIN}/api/oidc/authorization?state=1234abcedfdhf
      - OPENID_JWKS_ENDPOINT=https://auth.${HOMELAB_BASE_DOMAIN}/jwks.json
      - OPENID_ISSUER=https://auth.${HOMELAB_BASE_DOMAIN}
      - OPENID_REDIRECT_URI=https://remote-desktop-gateway.${HOMELAB_BASE_DOMAIN}
      - OPENID_USERNAME_CLAIM_TYPE=preferred_username
      - OPENID_GROUPS_CLAIM_TYPE=groups
      - OPENID_SCOPE=openid profile groups email

    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-guacamole.rule=Host(`remote-desktop-gateway.${HOMELAB_BASE_DOMAIN}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-guacamole.entrypoints=web,websecure

      # Redirect to /guacamole because they refuse to do it themselves.
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-guacamole-redirect-prefix.redirectregex.regex=^https://remote-desktop-gateway.${HOMELAB_BASE_DOMAIN}/$
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-guacamole-redirect-prefix.redirectregex.replacement=https://remote-desktop-gateway.${HOMELAB_BASE_DOMAIN}/guacamole
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-guacamole.middlewares=${COMPOSE_PROJECT_NAME}-guacamole-redirect-prefix

      - dashboard.group=Cloud
      - dashboard.name=Remote Desktop Gateway
      - dashboard.subtitle=Guacamole
      - dashboard.url=https://remote-desktop-gateway.${HOMELAB_BASE_DOMAIN}
      - dashboard.icon=fa fa-computer

  postgres:
    image: postgres:9.6
    volumes:
      - ./persistent/db:/var/lib/postgresql/data
      - ./data/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  reverse-proxy:
    external: true
