#!/usr/bin/env bash
set -e

BIN_PATH="$(dirname "$(realpath "$0")")/../bin"
source "${BIN_PATH}/homelab-shell-env"

env | sort | grep ^HOMELAB

read -n 1 -r -s -p "Press any key to close this window ..."
