#!/usr/bin/env bash
set -e

SERVICES=(
  'homelab.*'
)

echo "Restarting services ..."
systemctl restart "${SERVICES[@]}"

systemctl status --no-pager --full --lines 0 "${SERVICES[@]}"

read -n 1 -r -s -p "Press any key to close this window ..."
