version: "2"

services:
  survival_server:
    image: itzg/minecraft-bedrock-server
    env_file: env
    environment:
      SERVER_NAME: minecraft-bedrock-survival-server.${HOMELAB_BASE_DOMAIN}
      GAMEMODE: survival
      DIFFICULTY: normal
      # mikewhy709: 2535437042564979
      OPS: "2535437042564979"
      MEMBERS: "1234567890,0987654321"
    ports:
      - 21234:19132/udp
    volumes:
      - ./persistent/survival:/data

    # The examples given all have this set.
    # https://github.com/itzg/docker-minecraft-bedrock-server/tree/000a8dfbd27b388ceca622bf323d812d573001b4/examples
    stdin_open: true
    # The examples given all have this set.
    # https://github.com/itzg/docker-minecraft-bedrock-server/tree/000a8dfbd27b388ceca622bf323d812d573001b4/examples
    tty: true
